### PR TITLE
add .join({ wrap: fn })

### PR DESCRIPTION
**Pull request by juliangruber**
I need this for implementing throttling in Dat Desktop.

### CODE REVIEW

**Comment by juliangruber** [comment]
i'm not sure this is a good idea yet, let me test this in desktop first

**Comment by juliangruber** [comment]
this pattern isn't as nice as discovery swarm reads some custom props on the underlying stream. a throttle implementation would look something like this:

```js
const wrap = function (stream) {
  // this is the normal throttle logic
  const input = throttle(speed)
  const output = throttle(speed)

  input.pipe(stream).pipe(output)
  const throttled = duplex(input, output)

  // this is all the extra plumbing you have to do
  stream.on('error', throttled.emit.bind(throttled, 'error'))
  stream.on('handshake', throttled.emit.bind(throttled, 'handshake'))

  throttled.destroy = stream.destroy.bind(stream)

  Object.defineProperty(throttled, 'id', { get: () => stream.id })
  Object.defineProperty(throttled, 'remoteId', { get: () => stream.remoteId })

  return throttled
}
dat.joinNetwork({ wrap })
```

**Comment by juliangruber** [comment]
instead, this module (and thus also discovery-swarm) should let you connect streams yourself. I'm thinking about something like:

```js
disc({
  connect: (local, remote) => {
    local.pipe(throttle(speed)).pipe(remote).pipe(throttle(speed)).pipe(local)
  }
})
```

**Comment by juliangruber** [comment]
this is possible now through https://github.com/mafintosh/discovery-swarm/pull/29#event-1118506654 which floats in automatically :)

**Comment by juliangruber** [comment]
oh, so, I forgot to close this issue! Just pass `{ connect }` to `.join()` :)

**Comment by joehand** [comment]
Ha I couldn't tell if it was still needed =)

**Pull request closed without merging**
